from django.db import models

# Create your models here.
'''model class for patient data with autogenerated primary key, first name,
last name, and age'''
class Patient(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    age = models.IntegerField()

'''model class for patient data with autogenerated primary key, component name, 
component value, measured date, and patient id as a foreign key'''
class ClinicalData(models.Model):
    id = models.AutoField(primary_key=True)
    component_name = models.CharField(max_length=50)
    component_value = models.CharField(max_length=50)
    measured_date = models.DateTimeField(auto_now_add=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)

